---
- name: Configure systemd-journald
  hosts: myhost

  tasks:
    - name: Deploy the new configuration file
      template:
        src: j2/journald.conf.j2
        dest: /etc/systemd/journald.conf
      notify: restart journald

  handlers:
    - name: restart journald
      service:
        name: systemd-journald
        state: restarted
