---
- name: Turn Off Firefox DNF updates
  hosts: myhost
  connection: local

  tasks:
    - name: Update /etc/dnf/dnf.conf to include firefox to be updated
      lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "^exclude="
        state: absent

