---
- name: Install All the basic packages
  hosts: myhost
  connection: local

  vars:
    lifdict:
      - regexp: "^fastestmirror"
        line: "fastestmirror=true"
      - regexp: "^deltarpm"
        line: "deltarpm=true"

  tasks:
    - name: Install Packages
      dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Ensure DeltaRPM and Fastest Mirrors are enabled for DNF
      lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop: "{{ lifdict }}"

