---
- name: Install Atom, this cannot be installed using the package manager on Fedora, Centos
  hosts: myhost

  vars:
    BASEURL: "https://atom.io/"
    DLURL: "{{ BASEURL}}download/rpm"
    RPMFILE: "atom.rpm"

  tasks:
    - name: Gather Package facts
      package_facts:
        manager: auto

    - name: get current version online
      shell: curl {{ BASEURL }} 2>/dev/null | grep -e '\"version\">' | grep -o '[0-9]*\.[0-9]*\.[0-9]*'
      args:
        warn: false
      register: cur_version
      changed_when: false

    - name: 'DEBUG: check if ansible_facts.packages.atom exists'
      block:
        - name: Set installed_version fact
          set_fact:
            installed_version: "{{ ansible_facts['packages']['atom'][0]['version'] }}"
          when: ansible_facts.packages.atom is defined

        - name: Fail if Atom package is not installed
          fail:
          when: ansible_facts.packages.atom is not defined

      rescue:
        - name: Set installed_version to empty
          set_fact:
            installed_version: ""

    - name: Tasks to install Atom if the installed version is different from the online version
      block:
        - name: download Atom RPM file
          become: no
          get_url:
            url: "{{ DLURL }}"
            dest: "./{{ RPMFILE }}"
            tmp_dest: /tmp

        - name: install the atom package
          dnf:
            name: "{{ RPMFILE }}"
            state: latest

        - name: Remove the RPM file
          file:
            path: "{{ RPMFILE }}"
            state: absent

      when: (cur_version.stdout != installed_version)
