---
- name: Install All the basic packages
  hosts: myhost

  vars:
    lifdict:
      - regexp: "^fastestmirror"
        line: "fastestmirror=true"
      - regexp: "^deltarpm"
        line: "deltarpm=true"

  tasks:
    - name: Determine current Fedora version
      set_fact:
        cur_version: "{{ lookup('pipe', 'cat /etc/redhat-release | grep -E -o \"[0-9]{2}\"') | int }}"

    - name: Install Packages
      dnf:
        name: "{{ item }}"
        state: present
      loop: 
        - "{{ packages }}"
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ cur_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ cur_version }}.noarch.rpm"

    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Ensure DeltaRPM and Fastest Mirrors are enabled for DNF
      lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop: "{{ lifdict }}"

