---
- name: Install Freeplane, this cannot be installed using the package manager on Fedora, Centos
  hosts: myhost

  vars:
    DLURL: "https://sourceforge.net/projects/freeplane/files/latest/download"
    LOCALPATH: "./freeplane_bin.zip"
    APPPATH: "/opt"
    DESKTOPPATH: "~/.local/share/applications"
    FPDESKTOP: "{{ DESKTOPPATH }}/freeplane.desktop"
    DESKTOPTEMPL: "j2/freeplane-desktop.j2"

  tasks:

    - name: Check if Freeplane exists in /opt
      shell: find /opt -name "free*" -type d | grep -e 'freeplane-[0-9]*.[0-9]*.[0-9]*$'
      register: fp_test

    - debug:
        var: fp_test
